// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgqxwgwdbaukydrutzfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJncXh3Z3dkYmF1a3lkcnV0emZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzE3NTksImV4cCI6MjA3Mzk0Nzc1OX0.1ZusS1LT3t7Oe7zx_F5WAGnqyfdnst0BFtiRQOju8WY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});